data:extend({
	{
		type = "item",
		name = "yir_emdf7a_mn",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7a_mn_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_loco_big",
		order = "b-diesel2-2",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_emdf7a_mn",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7b_mn",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7b_mn_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_loco_big",
		order = "b-diesel2-1",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_emdf7b_mn",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7a_cr",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7a_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_loco_big",
		order = "b-diesel2-4",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_emdf7a_cr",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7b_cr",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7b_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_loco_big",
		order = "b-diesel2-3",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_emdf7b_cr",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_es44cr",
		icon = "__z_yira_american__/graphics/icons/ES44AC_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_loco_big",
		order = "b-diesel2-5",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_es44cr",
		weight = 200000,
	},

	{
		type = "item-with-entity-data",
		name = "yir_4a_container_cr",
		icon = "__z_yira_american__/graphics/icons/4a_container_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_cargowagons",
		order = "c2",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_4a_container_cr",
		weight = 200000,
	},
	{
		type = "item-with-entity-data",
		name = "yir_4a_clean_cr",
		icon = "__z_yira_american__/graphics/icons/4a_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_cargowagons",
		order = "c1",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_4a_clean_cr",
		weight = 200000,
	},
	{
		type = "item-with-entity-data",
		name = "yir_wagon_caboose_cr",
		icon = "__z_yira_american__/graphics/icons/2a_caboose_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_cargowagons_small",
		order = "e1",
		stack_size = 5,
		icon_size = 64,
		place_result = "yir_wagon_caboose_cr",
		weight = 200000,
	},
})