data:extend({
	{
		type = "item",
		name = "yir_emdf7a_mn",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7a_mn_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "d3",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_emdf7a_mn",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7b_mn",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7b_mn_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "d3",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_emdf7b_mn",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7a_cr",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7a_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "d3",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_emdf7a_cr",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_emdf7b_cr",
		icon = "__z_yira_american__/graphics/icons/yir_emdf7b_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "d3",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_emdf7b_cr",
		weight = 200000,
	},
	{
		type = "item",
		name = "yir_es44cr",
		icon = "__z_yira_american__/graphics/icons/ES44AC_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "cr1",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_es44cr",
		weight = 200000,
	},

	{
		type = "item-with-entity-data",
		name = "yir_4a_container_cr",
		icon = "__z_yira_american__/graphics/icons/4a_container_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "cr3",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_4a_container_cr",
		weight = 200000,
	},
	{
		type = "item-with-entity-data",
		name = "yir_4a_clean_cr",
		icon = "__z_yira_american__/graphics/icons/4a_cr_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "cr4",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_4a_clean_cr",
		weight = 200000,
	},
	{
		type = "item-with-entity-data",
		name = "yir_wagon_caboose_cr",
		icon = "__z_yira_american__/graphics/icons/2a_caboose_icon.png",
		group = "yuoki_railway",
		subgroup = "yir_americans",
		order = "cr2",
		stack_size = 5,
		icon_size = 32,
		place_result = "yir_wagon_caboose_cr",
		weight = 200000,
	},
})