functions = require("lib.functions")
local sounds = require("__base__.prototypes.entity.sounds")
local vanillaResistance = data.raw["cargo-wagon"]["cargo-wagon"].resistances

data:extend({
	{
		type = "cargo-wagon",
		name = "yir_4a_container_cr",
		icon = "__z_yira_american__/graphics/icons/4a_container_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 30,
		minable = {mining_time = 0.5, result = "yir_4a_container_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.5,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},

	{
		type = "cargo-wagon",
		name = "yir_4a_clean_cr",
		icon = "__z_yira_american__/graphics/icons/4a_cr_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 30,
		minable = {mining_time = 0.5, result = "yir_4a_clean_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, joint_distance = 4,
		weight = 1000,
		max_speed = 1.5,
		braking_force = 2,
		friction_force = 0.5,
		air_resistance = 0.01,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.5,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},

	{
		type = "cargo-wagon",
		name = "yir_wagon_caboose_cr",
		icon = "__z_yira_american__/graphics/icons/2a_caboose_icon.png",
		icon_size = 64,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 5,
		minable = {mining_time = 0.5, result = "yir_wagon_caboose_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 400,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 500,
		max_speed = 1.5,
		braking_force = 1,
		friction_force = 0.0015,
		air_resistance = 0.01,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.5,
		tie_distance = 50,
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},
})