functions = require("lib.functions")
local sounds = require("__base__.prototypes.entity.sounds")
local vanillaResistance = data.raw["cargo-wagon"]["cargo-wagon"].resistances

data:extend({
	{
		type = "cargo-wagon",
		name = "yir_4a_container_cr",
		icon = "__z_yira_american__/graphics/icons/4a_container_icon.png", icon_size = 32,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 30,
		minable = {mining_time = 1, result = "yir_4a_container_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, joint_distance = 4,
		weight = 1500,
		max_speed = 1.157, -- 250 km/h
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.8,
		pictures =
		{
			rotated = {
			priority = "very-low",
			width = 256,
			height = 256,
			back_equals_front = true,
			direction_count = 64,
			filename = "__z_yira_american__/graphics/4a_container_sheet.png",
			line_length = 8,
			lines_per_file = 8,
			shift = {0.42, -1.125}
			},
		},
		tie_distance = 50,
		open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75},
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},

	{
		type = "cargo-wagon",
		name = "yir_4a_clean_cr",
		icon = "__z_yira_american__/graphics/icons/4a_cr_icon.png", icon_size = 32,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 30,
		minable = {mining_time = 1, result = "yir_4a_clean_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 600,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
		selection_box = {{-1.0, -3}, {1, 3}},
		connection_distance = 3, joint_distance = 4,
		weight = 1500,
		max_speed = 1.157, -- 250 km/h
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.8,
		pictures =
		{
			rotated = {
			priority = "very-low",
			width = 256,
			height = 256,
			back_equals_front = true,
			direction_count = 64,
			filename = "__z_yira_american__/graphics/4a_cr_sheet.png",
			line_length = 8,
			lines_per_file = 8,
			shift = {0.42, -1.125}
			},
		},
		tie_distance = 50,
		open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75},
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},

	{
		type = "cargo-wagon",
		name = "yir_wagon_caboose_cr",
		icon = "__z_yira_american__/graphics/icons/2a_caboose_icon.png",icon_size = 32,
		flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
		inventory_size = 5,
		minable = {mining_time = 1, result = "yir_wagon_caboose_cr"},
		mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg"},
		max_health = 400,
		corpse = "medium-remnants",
		dying_explosion = "medium-explosion",
		collision_box = {{-0.6, -1.5}, {0.6, 1.5}},
		selection_box = {{-1, -2}, {1, 2}},
		weight = 600,
		max_speed = 0.926, -- 200 km/h
		braking_force = 2,
		friction_force = 0.0015,
		air_resistance = 0.002,
		connection_distance = 3.6,
		joint_distance = 1.8,
		energy_per_hit_point = 5,
		resistances = vanillaResistance,
		vertical_selection_shift = -0.5,
		pictures =
		{
			rotated = {
			priority = "very-low",
			width = 256,
			height = 256,
			back_equals_front = true,
			direction_count = 64,
			filename = "__z_yira_american__/graphics/2a_caboose_sheet.png",
			line_length = 8,
			lines_per_file = 8,
			shift = {0.42, -1.125}
			},
		},
		tie_distance = 50,
		open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85},
		close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75},
		working_sound = sounds.train_wagon_wheels,
		crash_trigger = functions.crash_trigger,
		wheels = functions.standard_train_wheels,
		drive_over_tie_trigger = functions.yir_drive_over_tie,
	},
})